name: Automated Workflow

on:
  workflow_dispatch:
    branches:
      - master
#      - install
  push:
    branches:
      - master
jobs:
  build:
    name: Hello from automated workflow
    runs-on: ubuntu-20.04
    steps:
      - run: echo Hello
