name: Manual workflow



on:
  workflow_dispatch:
  push:
    branches:
      - master
      - fake-noname-branch



jobs:
  build:
    name: Coverity Scan
    runs-on: ubuntu-20.04
    container: ubuntu:20.04



    ###
    ### Steps to run
    ###
    steps:



      ### Install build environment tools
      #
      - run: echo Hello manual
